spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd

mybatis:
  configuration:
    map-underscore-to-camel-case: true
#    server.tomcat.uri-encoding=UTF-8
server:
  port: 9000
